"""Batch calibration estimation utilities."""

from __future__ import annotations

from calib_sim.estimation.dataset import (
    BatchDataError,
    BatchSchemaError,
    CURRENT_SCHEMA_VERSION,
    REPO_ROOT,
    load_batch_dataset,
    load_device_config,
    load_evaluation_data,
)
from calib_sim.estimation.eval_metrics import evaluate_batch_result
from calib_sim.estimation.init_bootstrap import bootstrap_initial_guess, choose_anchor_frame, inertial_initial_guess_from_visual_solution
from calib_sim.estimation.noise_models import (
    ImuNoisePreset,
    TimingNoisePreset,
    VisionNoisePreset,
    load_noise_preset,
    load_imu_noise_preset,
    load_timing_noise_preset,
    load_vision_noise_preset,
)
from calib_sim.estimation.posterior import compute_laplace_posterior
from calib_sim.estimation.solve_batch_map import solve_visual_batch_map, solve_visual_inertial_batch_map
from calib_sim.estimation.types import (
    BatchCalibrationDataset,
    BatchCalibrationEvaluationData,
    BatchSolveResult,
    CameraFrame,
    CameraModelSnapshot,
    CameraPoseEstimationBridgeSnapshot,
    CameraTruthSample,
    DeviceCameraSnapshot,
    DeviceConfigSnapshot,
    DeviceImuSnapshot,
    GlobalVectorUncertaintySummary,
    ImuConventionSnapshot,
    DeviceMountSnapshot,
    EvalSummary,
    InitialGuess,
    ImuPacket,
    PoseUncertaintySummary,
    TagDetectionObservation,
    TagSpec,
    TagTruthSample,
    UncertaintySummary,
    VectorUncertaintySummary,
)

__all__ = [
    "BatchCalibrationDataset",
    "BatchCalibrationEvaluationData",
    "BatchDataError",
    "BatchSchemaError",
    "BatchSolveResult",
    "CameraFrame",
    "CameraModelSnapshot",
    "CameraPoseEstimationBridgeSnapshot",
    "CameraTruthSample",
    "CURRENT_SCHEMA_VERSION",
    "DeviceCameraSnapshot",
    "DeviceConfigSnapshot",
    "DeviceImuSnapshot",
    "GlobalVectorUncertaintySummary",
    "ImuConventionSnapshot",
    "DeviceMountSnapshot",
    "EvalSummary",
    "ImuNoisePreset",
    "ImuPacket",
    "InitialGuess",
    "PoseUncertaintySummary",
    "REPO_ROOT",
    "TagDetectionObservation",
    "TagSpec",
    "TagTruthSample",
    "TimingNoisePreset",
    "UncertaintySummary",
    "VectorUncertaintySummary",
    "bootstrap_initial_guess",
    "choose_anchor_frame",
    "inertial_initial_guess_from_visual_solution",
    "compute_laplace_posterior",
    "evaluate_batch_result",
    "VisionNoisePreset",
    "load_batch_dataset",
    "load_device_config",
    "load_evaluation_data",
    "load_imu_noise_preset",
    "load_noise_preset",
    "load_timing_noise_preset",
    "load_vision_noise_preset",
    "solve_visual_batch_map",
    "solve_visual_inertial_batch_map",
]
